#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &

bspc config border_width 1
bspc config border_radius 12
bspc config focused_border_color "#00AAFF"
bspc config normal_border_color "#0055BB"

bspc config window_gap 10

bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc config automatic_scheme spiral

exec --no-startup-id nm-applet

sudo systemctl start x11vnc

picom -b

nitrogen --restore
